const enc=new TextEncoder(),dec=new TextDecoder(); let tokenCache={value:'',expires:0};
function b64url(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'')}
function unb64url(v){const p='='.repeat((4-v.length%4)%4);const raw=atob(v.replace(/-/g,'+').replace(/_/g,'/')+p);return Uint8Array.from(raw,c=>c.charCodeAt(0))}
async function key(secret){if(!secret)throw new Error('DRIVE_ENCRYPTION_KEY/SESSION_SECRET não configurado');const digest=await crypto.subtle.digest('SHA-256',enc.encode(secret));return crypto.subtle.importKey('raw',digest,{name:'AES-GCM'},false,['encrypt','decrypt'])}
function secret(env){return env.DRIVE_ENCRYPTION_KEY||env.SESSION_SECRET||''}
async function hmac(env,value){if(!env.SESSION_SECRET)throw new Error('SESSION_SECRET não configurado');const k=await crypto.subtle.importKey('raw',enc.encode(env.SESSION_SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64url(new Uint8Array(await crypto.subtle.sign('HMAC',k,enc.encode(value))))}
export function driveRedirectUri(request){return new URL('/api/admin/google/callback',request.url).toString()}
export async function makeDriveState(env,request){const payload=b64url(enc.encode(JSON.stringify({exp:Date.now()+600000,origin:new URL(request.url).origin,nonce:crypto.randomUUID()})));return `${payload}.${await hmac(env,payload)}`}
export async function verifyDriveState(env,request,state){try{const[p,s]=String(state||'').split('.');if(!p||!s||s!==await hmac(env,p))return false;const d=JSON.parse(dec.decode(unb64url(p)));return Number(d.exp)>Date.now()&&d.origin===new URL(request.url).origin}catch{return false}}
async function ensure(env){if(!env.DB)throw new Error('D1 binding DB não configurado');await env.DB.prepare(`CREATE TABLE IF NOT EXISTS macabra_drive_auth(id INTEGER PRIMARY KEY CHECK(id=1),refresh_token_enc TEXT NOT NULL,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run()}
async function encrypt(sec,token){const iv=crypto.getRandomValues(new Uint8Array(12));const k=await key(sec);const cipher=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},k,enc.encode(token)));return `${b64url(iv)}.${b64url(cipher)}`}
async function decrypt(sec,packed){const[a,b]=String(packed).split('.');const k=await key(sec);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64url(a)},k,unb64url(b));return dec.decode(plain)}
export async function saveDriveRefreshToken(env,token){await ensure(env);const packed=await encrypt(secret(env),token);await env.DB.prepare(`INSERT INTO macabra_drive_auth(id,refresh_token_enc,updated_at) VALUES(1,?,CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET refresh_token_enc=excluded.refresh_token_enc,updated_at=CURRENT_TIMESTAMP`).bind(packed).run()}
export async function disconnectDrive(env){await ensure(env);await env.DB.prepare('DELETE FROM macabra_drive_auth WHERE id=1').run();tokenCache={value:'',expires:0}}
export async function loadDriveRefreshToken(env){await ensure(env);const row=await env.DB.prepare('SELECT refresh_token_enc FROM macabra_drive_auth WHERE id=1').first();if(!row?.refresh_token_enc)return '';return decrypt(secret(env),row.refresh_token_enc)}
export async function driveConnected(env){try{return Boolean(await loadDriveRefreshToken(env))}catch{return false}}
export async function getDriveAccessToken(env){if(tokenCache.value&&tokenCache.expires>Date.now()+60000)return tokenCache.value;if(!env.GOOGLE_DRIVE_CLIENT_ID||!env.GOOGLE_DRIVE_CLIENT_SECRET)throw new Error('Credenciais do Google Drive não configuradas');const refresh=await loadDriveRefreshToken(env);if(!refresh)throw new Error('Google Drive não conectado');const body=new URLSearchParams({client_id:env.GOOGLE_DRIVE_CLIENT_ID,client_secret:env.GOOGLE_DRIVE_CLIENT_SECRET,refresh_token:refresh,grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body});const d=await r.json().catch(()=>({}));if(!r.ok||!d.access_token)throw new Error(d.error_description||'Falha ao renovar acesso ao Google Drive');tokenCache={value:d.access_token,expires:Date.now()+(Number(d.expires_in)||3600)*1000};return d.access_token}
export async function uploadDriveFile(env,file,name){const folder=String(env.GOOGLE_DRIVE_FOLDER_ID||'').trim();if(!folder)throw new Error('GOOGLE_DRIVE_FOLDER_ID não configurado');const token=await getDriveAccessToken(env);const boundary=`mac_${crypto.randomUUID()}`;const meta=JSON.stringify({name,parents:[folder]});const body=new Blob([`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${meta}\r\n`,`--${boundary}\r\nContent-Type: ${file.type}\r\n\r\n`,file,`\r\n--${boundary}--`]);const r=await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&supportsAllDrives=true&fields=id,name,mimeType,size',{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':`multipart/related; boundary=${boundary}`},body});const d=await r.json().catch(()=>({}));if(!r.ok||!d.id)throw new Error(d.error?.message||'Falha ao enviar imagem ao Google Drive');return d}
export async function fetchDriveFile(env,id){const token=await getDriveAccessToken(env);return fetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(id)}?alt=media&supportsAllDrives=true`,{headers:{authorization:`Bearer ${token}`}})}
